#!/bin/bash
##
# \file       	Makefile-helper
# \library    	Documents
# \author     	Chris Ahlstrom
# \date       	2015-11-01
# \update     	2017-09-23
# \version    	$Revision$
# \license    	$XPC_SUITE_GPL_LICENSE$
#
# 		Makefile for the sequencer64-doc project.
#
# Note the new usage of gs (Ghostscript) to optimize the PDF.  Obviously, one
# must have Ghostscript installed.  This optimization reduces the near 40 Mb
# PDF down to about 4 Mb in size, with no significant reduction in quality.

MKERROR="no"

if [ "$1" == "clean" ] ; then

   pushd tex
   make clean
   popd

else

	echo "Building PDF using latexmk..."
   pushd tex
   make
   if [ $? != 0 ] ; then
      MKERROR="yes"
		echo "FATAL ERROR in processing TeX files!"
	else
		cp sequencer64-user-manual.pdf ../pdf/
		cp sequencer64-user-manual.pdf ../pdf/sequencer64-user-manual-unoptimized.pdf 
   fi
   popd

   if [ "$MKERROR" == "no" ] ; then
		if [ "$1" == "optimize" ] ; then
		pushd pdf
		mv sequencer64-user-manual.pdf s-temp.pdf
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dQUIET -dBATCH \
 -sOutputFile=sequencer64-user-manual.pdf s-temp.pdf
 		if [ $? == 0 ] ; then
			rm s-temp.pdf
		else
			echo "? Could not reduce the size of the PDF"
			mv s-temp.pdf sequencer64-user-manual.pdf
		fi
		popd
   	fi
	fi
fi

#******************************************************************************
# vim: ts=3 sw=3 noet ft=sh
#------------------------------------------------------------------------------
